# ============================================================
#  SCHOLARIS — Configuration base de données PostgreSQL
#  ⚠️  Ne jamais envoyer ce fichier sur Git !
#  Ajouter database.properties dans .gitignore
# ============================================================

# Connexion PostgreSQL
db.url=jdbc:postgresql://localhost:5432/scholaris_db
db.user=postgres
db.password=Mario_07
db.driver=org.postgresql.Driver

# Pool de connexions
db.pool.size=5
db.timeout=30000
